import Providers from "@/redux/Providers";
import "./globals.css";
import { Inter } from "next/font/google";
import Header from "@/components/modules/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: any;
}) {
  console.log(params);
  return (
    <html lang="en">
      <body className={`${inter.className} bg-gray-100 sm:mt-40`}>
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
